src/Web/WebMvc/Models/Search.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrderMyFoodApp.Web.WebMvc.Models
{
    public class Search
    {
        public int PageIndex { get; set; }
        public int PageSize { get; set; }
        public int Count { get; set; }
        public List<SearchItem> Data { get; set; }
    }
}

src/Web/WebMvc/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OrderMyFoodApp.Web.WebMvc.Models;
using OrderMyFoodApp.Web.WebMvc.Models.CartModels;
using OrderMyFoodApp.Web.WebMvc.Services;
using Polly.CircuitBreaker;

namespace WebMvc.Controllers
{
    [Authorize]
    public class CartController : Controller
    {

        private readonly ICartService _cartService;
        private readonly ISearchService _searchService;
        private readonly IIdentityService<ApplicationUser> _identityService;

        public CartController(IIdentityService<ApplicationUser> identityService, ICartService cartService, ISearchService searchService)
        {
            _identityService = identityService;
            _cartService = cartService;
            _searchService = searchService;



        }
        public IActionResult Index()
        {
            //try
            //{

            //    var user = _identityService.Get(HttpContext.User);
            //    var cart = await _cartService.GetCart(user);


            //    return View();
            //}
            //catch (BrokenCircuitException)
            //{
            //    // Catch error when CartApi is in circuit-opened mode                 
            //    HandleBrokenCircuitException();
            //}

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Dictionary<string, int> quantities, string action)
        {
            if (action == "[ Checkout ]")
            {
                // var order = _cartService.MapCartToOrder(cart);
                return RedirectToAction("Create", "Order");
                // return Redirect(Url.Action("Create", "Order", order));
            }

            try
            {
                var user = _identityService.Get(HttpContext.User);
                var cart = await _cartService.SetQuantities(user, quantities);
                var vm = await _cartService.UpdateCart(cart);


            }
            catch (BrokenCircuitException)
            {
                // Catch error when CartApi is in open circuit  mode                 
                HandleBrokenCircuitException();
            }

            return View();

        }

        public async Task<IActionResult> AddToCart(SearchItem productDetails)
        {
            try
            {
                if (productDetails.ItemId != null)
                {
                    var user = _identityService.Get(HttpContext.User);
                    var product = new CartItem()
                    {
                        Id = Guid.NewGuid().ToString(),
                        Quantity = 1,
                        ProductName = productDetails.Name,
                        PictureUrl = productDetails.ItemPictureUrl,
                        UnitPrice = productDetails.ItemPrice,
                        ProductId = productDetails.ItemId
                    };
                    await _cartService.AddItemToCart(user, product);
                }
                return RedirectToAction("Index", "Search");
            }
            catch (BrokenCircuitException)
            {
                // Catch error when CartApi is in circuit-opened mode                 
                HandleBrokenCircuitException();
            }

            return RedirectToAction("Index", "Search");

        }
        //public async Task WriteOutIdentityInfo()
        //{
        //    var identityToken =
        //        await HttpContext.Authentication.
        //         GetAuthenticateInfoAsync(OpenIdConnectParameterNames.IdToken);
        //    Debug.WriteLine($"Identity Token: {identityToken}");
        //    foreach (var claim in User.Claims)
        //    {
        //        Debug.WriteLine($"Claim Type: {claim.Type} - Claim Value : {claim.Value}");
        //    }

        //}

        private void HandleBrokenCircuitException()
        {
            TempData["BasketInoperativeMsg"] = "cart Service is inoperative, please try later on. (Business Msg Due to Circuit-Breaker)";
        }

    }
}

src/Web/WebMvc/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OrderMyFoodApp.Web.WebMvc.Services;
using OrderMyFoodApp.Web.WebMvc.ViewModels;
using WebMvc.Models;

namespace WebMvc.Controllers
{
   
    public class SearchController : Controller
    {
        private ISearchService _searchSvc;

        public SearchController(ISearchService searchSvc) =>
            _searchSvc = searchSvc;

        public async Task<IActionResult> Index(int? RestaurantsFilterApplied, int? page)
        {

            int itemsPage = 10;
            var search = await _searchSvc.GetSearchItems(page ?? 0, itemsPage, RestaurantsFilterApplied);
            var vm = new SearchIndexViewModel()
            {
                  
                SearchItems = search.Data,
                Restaurants = await _searchSvc.GetRestaurant(), 
                RestaurantFilterApplied = RestaurantsFilterApplied ?? 0,

                PaginationInfo = new PaginationInfo()
                {
                    ActualPage = page ?? 0,
                    ItemsPerPage = itemsPage, //search.Data.Count,
                    TotalItems =  search.Count,
                    TotalPages = (int)Math.Ceiling(((decimal)search.Count / itemsPage))
                }
            };

            vm.PaginationInfo.Next = (vm.PaginationInfo.ActualPage == vm.PaginationInfo.TotalPages - 1) ? "is-disabled" : "";
            vm.PaginationInfo.Previous = (vm.PaginationInfo.ActualPage == 0) ? "is-disabled" : "";

            return View(vm);
        }
        //[Authorize]
        //public async Task<IActionResult> About()
        //{
        //    ViewData["Message"] = "Your application description page.";
        //    var user = User as ClaimsPrincipal;

        //    var token = await HttpContext.GetTokenAsync("access_token");
        //    var idToken = await HttpContext.GetTokenAsync("id_token");
        //    foreach (var claim in user.Claims)
        //    {
        //        Debug.WriteLine($"Claim Type: {claim.Type} - Claim Value : {claim.Value}");
        //    }

        //    if (token != null)
        //    {
        //        ViewData["access_token"] = token;

        //    }
        //    if (idToken != null)
        //    {

        //        ViewData["id_token"] = idToken;
        //    }

        //    return View();
        //}

        [Authorize]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";


            return View();
        }




        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

src/Web/WebMvc/Views/Search/About.cshtml
@using Microsoft.AspNetCore.Authentication;
<h2>Access Token</h2>
<dl>
    @foreach (var claim in User.Claims)
    {
        <dt>@claim.Type</dt>
        <dd>@claim.Value</dd>

    }
    <dt>access token</dt>
    <dd>@await ViewContext.HttpContext.GetTokenAsync("access_token")</dd>
    <dt>refresh token</dt>
    <dd>@await ViewContext.HttpContext.GetTokenAsync("refresh_token")</dd>
</dl>

src/Web/WebMvc/Views/Search/Index.cshtml
@{
    ViewData["Title"] = "Catalog";
    @model OrderMyFoodApp.Web.WebMvc.ViewModels.SearchIndexViewModel
}
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/img1.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">

            </div>
        </div>
        <div class="item">
            <img src="~/images/img2.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">

            </div>
        </div>
        <div class="item">
            <img src="~/images/img3.jpg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">

            </div>
        </div>

    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<section class="esh-search-filters">
    <div class="container">
        <form asp-action="Index" asp-controller="Search" method="post">
            <label class="esh-search-label" data-title="brand">
                <select asp-for="@Model.RestaurantFilterApplied" asp-items="@Model.Restaurants" class="esh-search-filter"></select>
            </label>
            <input class="esh-search-send" type="image" src="~/images/arrow-right.svg" />
        </form>
    </div>
</section>
<div class="container">
    @if (Model.SearchItems.Count() > 0)
    {
        @Html.Partial("_pagination", Model.PaginationInfo)

        <div class="esh-search-items row">
            @foreach (var searchItem in Model.SearchItems)
            {
                <div class="esh-search-item col-md-4">
                    @Html.Partial("_product", searchItem)
                </div>
            }
        </div>

        @Html.Partial("_pagination", Model.PaginationInfo)
    }
    else
    {
        <div class="esh-search-items row">
            THERE ARE NO RESULTS THAT MATCH YOUR SEARCH
        </div>
    }
</div>

src/Web/WebMvc/Views/Search/_pagination.cshtml
@model OrderMyFoodApp.Web.WebMvc.ViewModels.PaginationInfo

<div class="esh-pager">
    <div class="container">
        <article class="esh-pager-wrapper row">
            <nav>
                <a class="esh-pager-item esh-pager-item--navigable @Model.Previous"
                   id="Previous"
                   asp-controller="Search"
                   asp-action="Index"
                   asp-route-page="@(Model.ActualPage -1)"
                   aria-label="Previous">
                    Previous
                </a>

                <span class="esh-pager-item">
                    Showing @Model.ItemsPerPage of @Model.TotalItems products - Page @(Model.ActualPage + 1) - @Model.TotalPages
                </span>

                <a class="esh-pager-item esh-pager-item--navigable @Model.Next"
                   id="Next"
                   asp-controller="Search"
                   asp-action="Index"
                   asp-route-page="@(Model.ActualPage + 1)"
                   aria-label="Next">
                    Next
                </a>
            </nav>
        </article>
    </div>
</div>

src/Web/WebMvc/Views/Search/_product.cshtml
@model OrderMyFoodApp.Web.WebMvc.Models.SearchItem




<form asp-controller="Cart" asp-action="AddToCart">
    <img class="esh-search-thumbnail" src="@Model.ItemPictureUrl" />
    <input class="esh-search-button" type="submit" value="[ ADD TO CART ]" />
    <div class="esh-catalog-name">
        <span>@Model.ItemName</span>
    </div>
    <div class="esh-catalog-price">
        <span>@Model.ItemPrice.ToString("N2")</span>
    </div>
    <input type="hidden" asp-for="@Model.Name " name="restaurant" />
    <input type="hidden" asp-for="@Model.RestaurantId" name="restaurantId" />
    
   
    <input type="hidden" asp-for="@Model.ItemId" name="id" />
    <input type="hidden" asp-for="@Model.ItemName" name="name" />
    <input type="hidden" asp-for="@Model.ItemPictureUrl" name="pictureUri" />
    <input type="hidden" asp-for="@Model.ItemPrice" name="price" />
</form>